version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.openjfx:javafx-controls
    versions:
    - 15.0.1
  - dependency-name: org.openjfx:javafx-fxml
    versions:
    - 15.0.1
  - dependency-name: org.openjfx:javafx-maven-plugin
    versions:
    - 0.0.5
  - dependency-name: com.google.inject:guice
    versions:
    - 4.2.3
